# ワークフローの名前
name: Manual Python Workflow

# ワークフローが実行されるタイミング
on:
  # メインブランチへのプッシュ時に自動実行
  push:
    branches:
      - main

  # GitHubのActionsタブから手動で実行できるようにする
  workflow_dispatch:

# ワークフローに含まれるジョブの定義
jobs:
  # 'build'という名前のジョブ
  build:
    # このジョブを実行する仮想環境
    runs-on: ubuntu-latest

    # ジョブ内で実行されるステップのリスト
    steps:
    - name: リポジトリのチェックアウト
      # リポジトリのコードを仮想環境にコピーする
      uses: actions/checkout@v4

    - name: Python環境のセットアップ
      # 指定されたバージョンのPythonをセットアップする
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: hello.pyの実行
      # 'python hello.py'コマンドを実行する
      run: python hello.py
